[package]
name = "redface"
version = "0.1.0"
authors = ["Abi Hafshin <abi@hafs.in>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.46.0"
simple-error = "0.2"
defer = "0.1.0"
